import type { Exercise } from '@/types';

export const DEFAULT_EXERCISES: Exercise[] = [
  {
    id: 'pull-ups-neutral',
    name: 'Pull-ups (Neutral Grip)',
    muscleGroup: 'back',
    defaultWeight: 0,
    weightIncrement: 2.5,
    isBodyweight: true,
    order: 0,
    active: true,
  },
  {
    id: 'incline-db-press',
    name: 'Incline DB Neutral Press',
    muscleGroup: 'chest',
    defaultWeight: 20,
    weightIncrement: 2,
    isBodyweight: false,
    order: 1,
    active: true,
  },
  {
    id: 'standing-press',
    name: 'Standing Press (DB/BB)',
    muscleGroup: 'shoulders',
    defaultWeight: 15,
    weightIncrement: 2.5,
    isBodyweight: false,
    order: 2,
    active: true,
  },
  {
    id: 'neutral-deadlift',
    name: 'Neutral-Grip Deadlifts',
    muscleGroup: 'back',
    defaultWeight: 60,
    weightIncrement: 5,
    isBodyweight: false,
    order: 3,
    active: true,
  },
  {
    id: 'incline-lateral-raise',
    name: 'Incline Lateral Raises (DB)',
    muscleGroup: 'shoulders',
    defaultWeight: 10,
    weightIncrement: 1,
    isBodyweight: false,
    order: 4,
    active: true,
  },
  {
    id: 'incline-db-triceps',
    name: 'Incline DB Triceps',
    muscleGroup: 'arms',
    defaultWeight: 12.5,
    weightIncrement: 1,
    isBodyweight: false,
    order: 5,
    active: true,
  },
  {
    id: 'incline-db-curls',
    name: 'Incline DB Curls',
    muscleGroup: 'arms',
    defaultWeight: 12.5,
    weightIncrement: 1,
    isBodyweight: false,
    order: 6,
    active: true,
  },
];
